version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:v1.9.0   # <-- новая версия с поддержкой строковых ID
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
    restart: unless-stopped